config/routes.rb
Rails.application.routes.draw do
  resources :bookings
  resources :spaces
  resources :charges
  post '/thankyou', to: 'charges#create'

  root 'pages#index'
  get '/login' => 'pages#login'
  get '/workersignup', to: 'pages#workersignup'
  get '/ownersignup', to: 'pages#ownersignup'

  devise_for :owners
  devise_for :workers

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/space.rb
class Space < ApplicationRecord
  belongs_to :owner
  mount_uploaders :images, ImageUploader
  serialize :images, Array
  validates_length_of :images, maximum: 6
  has_many :bookings

  validates :name, :street, :suburb, :state, :postcode, :country, presence: true
  geocoded_by :full_street_address

  after_validation :geocode
  attr_accessor :country_code


  def full_street_address
    [number, street, suburb, state, postcode, country].compact.join(',')
    #compact takes out any fields that are left blank when the form is filled out
    #join joins all the items with what's in the brackets in between the items
  end

end

app/controllers/spaces_controller.rb
class SpacesController < ApplicationController
  before_action :set_space, only: [:show, :edit, :update, :destroy]
  before_action :require_owner, only: [:new, :create]

  # GET /spaces
  # GET /spaces.json
  def index
    if params[:location]
        @spaces = Space.near(params[:location], 10)
    else
    @spaces = Space.all
  end
  end

  # GET /spaces/1
  # GET /spaces/1.json
  def show
    @bookings = Booking.all
  end

  # GET /spaces/new
  def new
    @space = Space.new
  end

  # GET /spaces/1/edit
  def edit
  end

  # POST /spaces
  # POST /spaces.json
  def create
    @space = Space.new(space_params)
    @space.owner_id = current_owner.id if current_owner
    respond_to do |format|
      if @space.save
        format.html { redirect_to @space, notice: 'Space was successfully created.' }
        format.json { render :show, status: :created, location: @space }
      else
        format.html { render :new }
        format.json { render json: @space.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /spaces/1
  # PATCH/PUT /spaces/1.json
  def update
    respond_to do |format|
      if @space.update(space_params)
        format.html { redirect_to @space, notice: 'Space was successfully updated.' }
        format.json { render :show, status: :ok, location: @space }
      else
        format.html { render :edit }
        format.json { render json: @space.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /spaces/1
  # DELETE /spaces/1.json
  def destroy
    @space.destroy
    respond_to do |format|
      format.html { redirect_to spaces_url, notice: 'Space was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_space
      @space = Space.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def space_params
      params.require(:space).permit(:owner_id, :description, :wifi, :food, :meetroom, :price, :approved, :location, {images: []}, :name, :number, :street, :suburb, :postcode, :state, :country)
    end

    def require_owner
      if !current_owner
        flash[:info] = "You are not allowed to access that page"
        redirect_to root_path
      end
    end


end

app/helpers/spaces_helper.rb
module SpacesHelper
end

app/views/spaces/_form.html.erb
<%= form_for(space) do |f| %>
  <% if space.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(space.errors.count, "error") %> prohibited this space from being saved:</h2>

      <ul>
      <% space.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_area :name %>
  </div>

  <div class="field">
    <%= f.label :number %>
    <%= f.text_area :number %>
  </div>

  <div class="field">
    <%= f.label :street %>
    <%= f.text_area :street %>
  </div>

  <div class="field">
    <%= f.label :suburb %>
    <%= f.text_area :suburb %>
  </div>

  <div class="field">
    <%= f.label :state %>
    <%= f.text_field :state, collection: ['NSW', 'QLD', 'VIC', 'WA', 'SA', 'NT'], as: :radio_buttons%>
  </div>

  <div class="field">
    <%= f.label :postcode %>
    <%= f.text_area :postcode %>
  </div>

  <div class="field">
    <%= f.label :country %>
    <%= f.text_field :country, priority: ['Australia', 'New Zealand'] %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :wifi %>
    <%= f.check_box :wifi %>
  </div>

  <div class="field">
    <%= f.label :food %>
    <%= f.check_box :food %>
  </div>

  <div class="field">
    <%= f.label :meetroom %>
    <%= f.check_box :meetroom %>
  </div>

  <div class="field">
    <%= f.label :price %>
    <%= f.text_field :price %>
  </div>

  <div class="field">
    <%= f.label :images %>
    <%= f.file_field :images, multiple: true %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/spaces/edit.html.erb
<h1>Editing Space</h1>

<%= render 'form', space: @space %>

<%= link_to 'Show', @space %> |
<%= link_to 'Back', spaces_path %>

app/views/spaces/index.html.erb
<p id="notice"><%= notice %></p>
<div class="container howitworks">
  <% @spaces.each do |space| %>
  <div class="row cards">
    <div class="card">
    <div class="card col-xs-12 col-sm-4 col-sm-offset-1 box">
      <%= image_tag(space.images.first, class: "style-image card-img-top")%>
        <div class="card-block">
          <h4 class="card-title"><%= space.name %></h4>
          <p class="card-text"><%= space.description%></p>
          <%= space.bookings.each do |find| %>
          <%= find.worker.firstname %>
          <% end %>
          <button type="button" class="btn btn-default" style="margin-bottom: 50px;">
          <%= link_to('Book!', space) %>
          </button>
        </div>
    </div>
  </div>
    <% end %>
  </div>
<%= link_to 'New Space', new_space_path %>

app/views/spaces/new.html.erb
<h1>New Space</h1>

<%= render 'form', space: @space %>

<%= link_to 'Back', spaces_path %>

app/views/spaces/show.html.erb
<div class="container">

  <%= @space.bookings.each do |booking| %>
  <%= booking.worker.email %>
  <%end%>



<div id="space-carousel" class="carousel slide" data-ride="carousel">
  <div class="carousel-inner">
    <% @space.images.each_with_index do |image, i| %>
      <% if i == 0%>
        <div class="item active">
      <% else%>
        <div class="item">
      <% end %>
      <%= image_tag(image, style: "width: 100%; height: auto")%>
    </div>
    <% end %>
  </div>
<!-- Controls -->
<% if @space.images.count !=1 %>
  <a class="left carousel-control" href="#space-carousel" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left"></span>
  </a>
  <a class="right carousel-control" href="#space-carousel" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right"></span>
  </a>
<% end %>
</div> <!-- Carousel -->

<div class=well>
<%= bookings = @space.bookings.select{ |look| look.date == Date.today } %>
<%= bookings.each do |now| %>
<%= now.worker.firstname %>
<%= image_tag(now.worker.photo) %>
<%end%>
</div>

<div class="row">
<div class="col-md-5">
<% if current_worker %>
 <%= month_calendar do |date| %>
    <%= content_tag :div, class: "day", data: {date: date} do %>
      <%= date.day %>
    <% end %>
  <% end %>
<% else %>
  <%= month_calendar do |date| %>
  <%= date.day %>
  <% end %>
<% end %>
</div>

<div class="col-md-5 col-md-offset-1">
<p>
  <strong>Name:</strong>
  <%= @space.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @space.description %>
</p>

<p>
  <strong>Wifi:</strong>
  <%= @space.wifi %>
</p>

<p>
  <strong>Food:</strong>
  <%= @space.food %>
</p>

<p>
  <strong>Meetroom:</strong>
  <%= @space.meetroom %>
</p>

<p>
  <strong>Price:</strong>
  <%= @space.price %>
</p>

<p>
  <strong>Location:</strong>
  <%= @space.location %>
</p>

<%= link_to 'Edit', edit_space_path(@space) %> |
<%= link_to 'Back', spaces_path %>
</div>
</div>
</div>


<script>
$(document).ready(function(){
  $('.day').click(function () {
    var date = $(this).attr('data-date').replace(/\"/g, "");
    location.href = "/bookings/new?date=" + date + "&space=" + <%= @space.id %>
  })
});
</script>

<div id="map"></div>
<script>
      function initMap() {
        var myLatLng = {lat: <%= @space.latitude %>, lng: <%= @space.longitude %>};

        var map = new google.maps.Map(document.getElementById('map'), {
          zoom: 15,
          center: myLatLng
        });

        var marker = new google.maps.Marker({
          position: myLatLng,
          map: map,
          title: '<%= @space.name %>'
        });
      }
    </script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCwri5aJWdAdV0pt265oqOJKHiGlOtjmUo&callback=initMap"
  async defer>
</script>
</div>