config/routes.rb
Rails.application.routes.draw do
  resources :bookings
  resources :spaces
  resources :charges
  post '/thankyou', to: 'charges#create'

  root 'pages#index'
  get '/login' => 'pages#login'
  get '/workersignup', to: 'pages#workersignup'
  get '/ownersignup', to: 'pages#ownersignup'

  devise_for :owners
  devise_for :workers

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/partials/_footer.html.erb
  <footer class="footer">
      <div class="container">
        <div class="row">
          <div class="col-sm-5 col-xs-12 col-sm-offset-1">
          <ul><a href="/about">About</a><br>
          <a href="/terms">Terms</a><br>
          <a href="/privacy">Privacy</a></ul>
          </div>
        <p class="text-muted"></p>
          <div class="col-sm-5 col-xs-12">
            <h4 class="new_space">Own a space?</h4>
            <p class="space_register">
              If you own a beautiful space and can provide workers with a new location
            to get shit done, then sign up here. Create a listing, tailor your offering and wait
            to see your space realise its potential.
          </p>
            <button type="button" class="btn btn-default">
            <%= link_to('Get Started', ownersignup_path) %>
            </button>
            </div>
    </div>
  </footer>

app/views/partials/_nav.html.erb
<nav class="navbar navbar-default mynav">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a> <%=link_to('Workup', root_path, :class=>"navbar-brand")%></a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="#">How it works</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if worker_signed_in? || owner_signed_in? %>
      <li>
      <%= link_to('Logout', destroy_worker_session_path, :method => :delete) %>
      </li>
      <% if worker_signed_in? %>
      <li>
        <%= link_to('Edit registration', edit_worker_registration_path) %>
     </li>
     <% else %>
      <%= link_to 'Create a space!', new_space_path, class: "btn btn-default" %>
      <%= link_to('Edit registration', edit_owner_registration_path) %>
     <% end %>
        <% else %>
          <li>
          <%= link_to('Login', login_path)  %>
          </li>

          <li>
     <%= link_to('Register', workersignup_path)  %>
     </li>
    <% end %>

      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/partials/_ownerlogin.html.erb
<h2>Log in</h2>

<%= form_for(:owner, url: session_path(:owner)) do |f| %>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.email_field :email, autofocus: true %>
  </div>

  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password, autocomplete: "off" %>
  </div>

  <% if devise_mapping.rememberable? -%>
    <div class="field">
      <%= f.check_box :remember_me %>
      <%= f.label :remember_me %>
    </div>
  <% end -%>

  <div class="actions">
    <%= f.submit "Log in" %>
  </div>
<% end %>

<%= render "owners/shared/links" %>

app/views/partials/_ownersignup.html.erb
<h2>Sign up</h2>

<%= form_for(:owner, url: registration_path(:owner)) do |f| %>
  <%= devise_error_messages! %>

  <div class="field">
    <%= f.label :username %><br />
    <%= f.text_field :username, autofocus: true %>
  </div>

  <div class="field">
    <%= f.label :abn %><br />
    <%= f.text_field :abn, autofocus: true %>
  </div>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.email_field :email, autofocus: true %>
  </div>

  <div class="field">
    <%= f.label :password %>
    <% if @minimum_password_length %>
    <em>(<%= @minimum_password_length %> characters minimum)</em>
    <% end %><br />
    <%= f.password_field :password, autocomplete: "off" %>
  </div>

  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation, autocomplete: "off" %>
  </div>

  <div class="actions">
    <%= f.submit "Sign up" %>
  </div>
<% end %>

<%= render "owners/shared/links" %>

app/views/partials/_workerlogin.html.erb
<h2>Log in</h2>

<%= form_for(:worker, url: session_path(:worker)) do |f| %>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.email_field :email, autofocus: true %>
  </div>

  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password, autocomplete: "off" %>
  </div>

  <% if devise_mapping.rememberable? -%>
    <div class="field">
      <%= f.check_box :remember_me %>
      <%= f.label :remember_me %>
    </div>
  <% end -%>

  <div class="actions">
    <%= f.submit "Log in" %>
  </div>
<% end %>

<%= render "workers/shared/links" %>

app/views/partials/_workersignup.html.erb
<h2>Sign up</h2>

<%= form_for(:worker, url: registration_path(:worker)) do |f| %>
  <%= devise_error_messages! %>

  <div class="field">
    <%= f.label :firstname %><br />
    <%= f.text_field :firstname, autofocus: true %>
  </div>

  <div class="field">
    <%= f.label :lastname %><br />
    <%= f.text_field :lastname, autofocus: true %>
  </div>

  <div class="field">
    <%= f.label :job %><br />
    <%= f.text_field :job, autofocus: true %>
  </div>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.email_field :email, autofocus: true %>
  </div>

  <div class="field">
    <%= f.label :password %>
    <% if @minimum_password_length %>
    <em>(<%= @minimum_password_length %> characters minimum)</em>
    <% end %><br />
    <%= f.password_field :password, autocomplete: "off" %>
  </div>

  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation, autocomplete: "off" %>
  </div>

  <div class="field">
    <%= f.label :photo %>
    <%= f.file_field :photo %>
  </div>

  <div class="actions">
    <%= f.submit "Sign up" %>
  </div>
<% end %>

<%= render "workers/shared/links" %>